name: Compile

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Nuke
        run: ./Build/Build.cmd --skip CreateInstaller