name: CreatePackage

on:
  push:
    branches:
      - master

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Nuke
        run: ./Build/Build.cmd
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RevitLookup
          path: output